<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Cylinder" Id="{f6a3a8d9-e4ba-4cdf-b01a-dbe0b512db31}" SpecialFunc="None">
    <Declaration><![CDATA[// IO元件
FUNCTION_BLOCK PUBLIC Cylinder
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Cylinder">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>