<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="TurboPump" Id="{36053571-f0f3-40e3-af8c-80f564be8382}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TurboPump
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TurboPump">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>