<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{708160a4-93d9-4013-9713-4347d7805f45}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i : int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := i + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>